[mypy]
plugins = pydantic.mypy
strict = True
enable_incomplete_feature = NewGenericSyntax
 
[mypy-kubernetes.*]
ignore_missing_imports = True
 
[mypy-boto3]
ignore_missing_imports = True
 
[mypy-sqlalchemy]
ignore_missing_imports = True
 
[mypy-dataikuapi.*]
ignore_missing_imports = True
 
[mypy-confluent_kafka.*]
ignore_missing_imports = True
 
[mypy-botocore]
ignore_missing_imports = True
 
[mypy-smart_open]
ignore_missing_imports = True
 
[mypy-jsonpath_ng]
ignore_missing_imports = True
 
[mypy-xmltodict]
ignore_missing_imports = True
 
[mypy-jsonschema]
ignore_missing_imports = True
 
[mypy-pandas]
ignore_missing_imports = True
 
[mypy-pymqi]
ignore_missing_imports = True
 
[mypy-pymqi.*]
ignore_missing_imports = True